services:
  llm:
    container_name: llm
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/" ]
      interval: 60s
      timeout: 10s
      retries: 5